name: pobronson
favicon: null
layout_spectrum: 0.8043515200261027
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: stars
    item: null
    url: null
typography_spectrum: 0.27022867277264595
